### ISSUE TITLE
More Info causes YARG author finder info to disappear

### ISSUE THREAD

**Issue by shny-scott** [jnackmclain/rock-band-3-deluxe#1065]
**Describe the bug**
Opening "more info" causes YARG rings to forget their author finder info. The song must be scrolled off of to refresh author finder.

**To Reproduce**
1. Go to the song list
2. Press yellow to open the info screen, and close it
3. See error

**Expected behavior**
it doesn't do that

**Screenshots**
![Image](https://github.com/user-attachments/assets/835326cb-d349-4b88-a81f-d0f8915b8cea)

**Game Information**
 - Platform: RPCS3
 - Version: 1.1.0-nightly+1e2eaec86 (self-built)
 - Song Count: 4031

**Additional context**

**Comment by jnackmclain** [comment]
fixed in latest dev

**Comment by shny-scott** [comment]
Not completely fixed. Changing any filter/sort setting causes the same issue on nightly 98673fd2.

![Image](https://github.com/user-attachments/assets/659f7967-9473-47cc-88f8-ac6d17445798)

**Comment by jnackmclain** [comment]
fixed
