### ISSUE TITLE
Same Custom Texture When Changed and Default Venue On Startup (PS3 Real Hardware)

### ISSUE THREAD

**Issue by apple754** [jnackmclain/rock-band-3-deluxe#1302]
For some reason, the custom textures preset I had last stays on when I change into a new theme. This only happens on the Overdrive meter, I don't see it happening on other textures. For ex. When I go into the RB4 custom textures preset since everything is all the textures from RB4, the overdrive's "custom textures" stays the same to RB3's which is the default texture

Also when I load up the game, the venue doesn't seem to stay on the specific venue I picked, Charles Pub always gets selected as the first venue

It started happening when I downloaded the updated pkg file and I'm still confused why one custom texture is only being stuck to one when I change them and a venue I didn't even pick the last time I played

**Comment by Kazzran** [comment]
I'm having the same venue issue where my selected venue doesn't stick between game sessions. PS3 real hardware. I usually have my venue set to None since it helps with performance and loading times but with the latest version I've needed to re-select it each time I boot up the software.

**Comment by lunalawl** [comment]
Overdrive bar texture has been fixed

**Comment by apple754** [comment]
It's me again, good job for fixing the overdrive bar texture but you guys
still didn't fix the bug where the venue is stuck to the Charles Pub
everytime I boot up the game rather than the last venue I chose

**Comment by Aloquendiar** [comment]
As far as I remember, Charles Pub is a single visual error that occurs when you place random venues; even if Overshell mentions that venue, it doesn't mean that's the selected venue.
